language: php

matrix:
  include:
    # linux tests
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: nightly
    # windows tests
    # https://travis-ci.community/t/where-to-contribute-php-support-for-windows/304
    - os: windows
      language: sh
      before_install:
        - choco install php
        - choco install composer 
        - choco install make
        - export PATH=/c/tools/php72:$PATH

  # allow php nightly to fail until https://travis-ci.community/t/php-nightly-now-requires-oniguruma/2237 is fixed
  allow_failures:
    - php: nightly

install: make install
script:
  - make test
  - if [[ $TRAVIS_PHP_VERSION = "7.3" || $TRAVIS_PHP_VERSION = "nightly" ]]; then true; else make check-style; fi
  - make coverage

